version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/dev.db
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/dev.db:/app/dev.db
    networks:
      - chat-network

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
